# FRBlip quick start

In [1]:
import numpy as np
import pandas as pd

import frblip as frb

import matplotlib.pyplot as plt

## Create a mock of Cosmic Bursts

In [2]:
mock = frb.blips(random_state=42)

get the redshift:

In [3]:
mock.redshift

array([13.7585392 ,  2.12335282,  3.7041686 , ...,  2.61098291,
        5.00125187,  2.90516625])

Luminosity distance:

In [4]:
mock.luminosity_distance

<Quantity [152042.42404822,  17145.10400473,  33500.66419704, ...,
            22031.5637861 ,  47744.42807441,  25056.26482523] Mpc>

Note that frblip uses units from astropy package

possible quantities and methods:

In [5]:
mock.__dict__.keys()

dict_keys(['duration', 'zmin', 'zmax', 'log_L0', 'log_Lstar', 'phistar', 'gamma', 'w_mean', 'w_std', '_spec_idx_dist', 'ra_range', 'dec_range', 'low_frequency', 'high_frequency', 'low_frequency_cal', 'high_frequency_cal', 'igm_model', 'free_electron_bias', 'cosmology', 'host_dist', 'host_source', 'host_model', 'emission_frame', 'start', 'gal_nside', 'gal_method', 'random_state', 'area', '_xmin', '_lumdist', '_cosmology', '_zdist', 'sky_rate', 'size', 'rate', 'params', 'spectral_index', 'redshift', 'luminosity_distance', 'log_luminosity', '_luminosity', 'flux', '_energy_normalization'])

Load a Radio Telescope:

In [6]:
bingo = frb.telescope()

Perform observations on a mock

In [7]:
mock.observe(bingo)

Performing observation for telescope OBS_0...
Computing positions for 106416 sources at site lon=-38.268 deg, lat=-7.041 deg, height=379.000 m.



The results are storage on observations property:

In [8]:
mock.observations

{'OBS_0': <frblip.observation.Observation at 0x7f14d9b368c0>}

Computing signal to noise ratio:

In [9]:
mock.signal_to_noise()

<xarray.DataArray (FRB: 106416, OBS_0: 28)>
<COO: shape=(106416, 28), dtype=float64, nnz=16428, fill_value=0.0>
Dimensions without coordinates: FRB, OBS_0

Note that the information is given as a sparse array. To convert it you must pass True to `todense` argument:

In [10]:
mock.signal_to_noise(todense=True)

<xarray.DataArray (FRB: 106416, OBS_0: 28)>
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
Dimensions without coordinates: FRB, OBS_0

To compute the total value over beams we pass True to the `total` argument

In [11]:
mock.signal_to_noise(total=True, todense=True)

<xarray.DataArray (FRB: 106416)>
array([0., 0., 0., ..., 0., 0., 0.])
Dimensions without coordinates: FRB

The function `triggers` returns if a FRB is observed given minima signal to noise values, default value is range(1, 11):

In [12]:
mock.triggers(todense=True)

<xarray.DataArray (FRB: 106416, OBS_0: 28, SNR: 10)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10
Dimensions without coordinates: FRB, OBS_0

In [13]:
mock.triggers(todense=True, snr=range(5, 16))

<xarray.DataArray (FRB: 106416, OBS_0: 28, SNR: 11)>
array([[[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
...
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]])
Coordinates:
  * SNR      (SNR) int64 5 6 7 8 9 10 11 12 13 14 15
Dimensions without coordinates: FRB, OBS_0

`counts` method returns the number of observed FRB:

In [14]:
mock.counts()

<xarray.DataArray (OBS_0: 28, SNR: 10)>
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10
Dimensions without coordinates: OBS_0

In [15]:
mock.counts(total=True)

<xarray.DataArray (SNR: 10)>
array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Coordinates:
  * SNR      (SNR) int64 1 2 3 4 5 6 7 8 9 10

In [16]:
mock.counts(total=True, snr=range(5, 16))

<xarray.DataArray (SNR: 11)>
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
Coordinates:
  * SNR      (SNR) int64 5 6 7 8 9 10 11 12 13 14 15

In [17]:
mock.catalog()

{'spectral_index': array([1.97695777]),
 'redshift': array([0.25528921]),
 'luminosity_distance': <Quantity [1332.66079159] Mpc>,
 'log_luminosity': <Dex [42.52790725] dex(erg / s)>,
 'flux': <Quantity [1586.92739793] Jy MHz>,
 'right_ascension': <Longitude [356.1787995] deg>,
 'declination': <Latitude [-9.92482655] deg>,
 'alt': <Latitude [86.93020299] deg>,
 'az': <Longitude [206.47583255] deg>,
 'obstime': <Time object: scale='utc' format='iso' value=['2024-08-02 05:39:22.132']>,
 'signal_to_noise': <xarray.DataArray (FRB: 1, OBS_0: 28)>
 array([[1.19451256e-072, 1.91329475e-022, 1.01808795e+000,
         1.04117241e-012, 8.29481843e-061, 2.17267741e-027,
         4.15268573e-014, 2.40354352e-009, 8.72385683e-083,
         6.08889060e-067, 8.12665915e-062, 1.32307720e-039,
         1.06110310e-139, 6.78540390e-139, 1.29178559e-141,
         3.03127762e-104, 8.44694813e-225, 1.50586972e-238,
         1.66860542e-247, 2.89839096e-197, 0.00000000e+000,
         0.00000000e+000, 0.00000